FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9-slim

WORKDIR /app
ENV PYTHONPATH=/app/src
COPY . .
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --upgrade pip
#RUN /app/requirements.sh
RUN apt-get update && apt-get install -y vim
RUN apt-get update && apt-get install -y procps net-tools



